VAR
largura, comprimento, area: real

INICIO
// solicita a largura do terreno
escreva("Digite a largura do terreno em metros: ")
leia(largura)

// solicita o comprimento do terreno
escreva("Digite o comprimento do terreno em metros: ")
leia(comprimento)

// calcula a área do terreno
area <- largura * comprimento

// exibe a área do terreno
escreva("A área do terreno é ", area, " metros quadrados.")

FIMALGORITMO