VAR
num1, num2: real

INICIO
// solicita o primeiro número ao usuário e converte para número
escreva("Digite o primeiro número: ")
leia(num1)

// solicita o segundo número ao usuário e converte para número
escreva("Digite o segundo número: ")
leia(num2)

// verifica se os números são iguais
se (num1 = num2) entao
escreva("Números iguais")
senao
se (num1 > num2) entao
escreva("O maior número é: ", num1)
senao
escreva("O maior número é: ", num2)
FIMSE
FIMSE

FIMALGORITMO